### ISSUE TITLE
切换buffer后，原来保持折叠的函数，会因为更新后，函数会展开并显示其中的变量

### ISSUE THREAD

**Issue by Peter-Chou** [liushihao456/symbols-outline.el#10]
切换buffer后，原来保持折叠的函数，会因为更新后，函数会展开并显示其中的变量。能否symbols-outline打开后，直接切换buffer设置保持不变呀，就是一致保持函数折叠？

**Comment by liushihao456** [comment]
是个bug，已经修复了，等更新后再试试

**Comment by Peter-Chou** [comment]
谢谢作者，的确修复了
