### ISSUE TITLE
当左右两个window为相同buffer时，从左边window跳转到右边window后再进入到symbols-outline 选择function跳转后，错误的window（左边）的跳转到对应的方法了

### ISSUE THREAD

**Issue by Peter-Chou** [liushihao456/symbols-outline.el#11]
当左右两个window都是相同buffer时，从左边window跳转到右边window后再进入到symbols-outline buffer选择function跳转后，错误的window（左边）的跳转到对应的方法了。我的理解应该时右边window发生变化。这个我感觉应该是个bug

**Comment by liushihao456** [comment]
修正了。等更新后试试~

**Comment by Peter-Chou** [comment]
的确修复了，非常感谢作者，非常好的包
