### ISSUE TITLE
多client的项目无法正常工作

### ISSUE THREAD

**Issue by Peter-Chou** [liushihao456/symbols-outline.el#2]
Java项目中因为lsp-mode 会启动两个client（jdtls负责java的，boot-ls负责yaml的）运行 `symbols-outline-show` 报以下错误：

```
Error processing message (wrong-type-argument number-or-marker-p nil).
```

我之后尝试重启emacs后，首先打开python项目（只有pyright client），`symbols-outline-show`运行正常，然后再随即打开Java项目也可以正常运行。  

或者我在Java项目中设置 `lsp-java-boot-enabled nil` 关闭boot-ls，然后直接Java项目也能正常运行。

我估计报错是不是因为java项目有两个client，才导致的问题。如果要排查Java项目问题的话，代码可以用https://github.com/BuntyRaghani/spring-boot-hello-world 这个demo。

**Comment by liushihao456** [comment]
我这边试了一下没出错啊。我对spring不熟，你可以帮我看看我这里boot-ls和jdtls是不是都启动了？
![1695628994929](https://github.com/liushihao456/symbols-outline.el/assets/28855328/0f62007a-65e8-464d-9ddf-4e26543516a9)

**Comment by Peter-Chou** [comment]
boot-ls 应该没正确启动，正常启动的话 状态不是starting  
![image](https://github.com/liushihao456/symbols-outline.el/assets/28672146/c7bb89c6-b753-40a1-bc94-99b2010d3bca)
