### ISSUE TITLE
gui也可以选择使用nerd-icons

### ISSUE THREAD

**Issue by Peter-Chou** [liushihao456/symbols-outline.el#3]
大佬能不能gui也开一个选项，可以在svg 和nerd-icons上进行选择呀，我这里svg显示不出来，TUI里的nerd-icons能很正常显示。

**Comment by liushihao456** [comment]
加了`symbols-outline-use-nerd-icon-in-gui`。试试？

**Comment by Peter-Chou** [comment]
嗯嗯 搞定啦，谢谢
