### ISSUE TITLE
Feature request: Mouse support

### ISSUE THREAD

**Issue by samebchase** [liushihao456/symbols-outline.el#4]
Hi, Thanks for making this! It's helpful and useful!

I was wondering if it were possible to enable mouse support, so that when we click on the symbol, it navigates us, the same way hitting `RET` would do.

Sometimes, it is faster to use the mouse, so was wondering if this support could be added.

**Comment by liushihao456** [comment]
I'm not very familiar with emacs' mouse API so it would take some time before I could implement it. In the meantime PRs would be welcome.

**Comment by samebchase** [comment]
Cool thanks!

**Comment by liushihao456** [comment]
Added some basic mouse support. Have a try!

**Comment by samebchase** [comment]
@liushihao456 oh fantastic let me try this out!
