### ISSUE TITLE
error in process filter

### ISSUE THREAD

**Issue by artelse** [liushihao456/symbols-outline.el#5]
Installed the package and in the side window nothing is displayed. However, when I hit RET, it jumps to the first line of my python file. 
I tested with `ctags` and my `eglot` setup and got these errors respectively:
`error in process filter: mapc: Wrong type argument: number-or-marker-p, nil`
`error in process filter: Wrong type argument: number-or-marker-p, nil`
and
`error in process filter: symbols-outline-lsp--convert-internal: Wrong type argument: number-or-marker-p, nil`
`error in process filter: Wrong type argument: number-or-marker-p, nil`

Let me know if you want me to test anything.

**Comment by liushihao456** [comment]
When using `ctags`, what is the content in the buffer `*symbols-outline-ctags-output*`?

**Comment by artelse** [comment]
Ok, that shows:
```
/usr/local/bin/ctags: unrecognized option '--output-format=json'
	Try '/usr/local/bin/ctags --help' for a complete list of options.
```
`ctags --help` doesn't show the `--output-format` option, however in the online documentation it should. The Emacs version I use is compiled with `json` enabled.

The version of ctags is:
```
 /usr/local/bin/ctags -V 
ctags (GNU Emacs 30.0.50)
```

**Comment by liushihao456** [comment]
I see. Please don't use Emacs' ctags. Use universal ctags instead.

**Comment by artelse** [comment]
Installed `ctags-universal` and set `symbols-outline-ctags-executable` accordingly. Now the outline window shows the function names in a python buffer, but not the functions inside classes or variables.  An elisp buffer works as expected.
Edit: checked `ctags-universal --list-kinds=python` and it has good support for python in its parser; i.e.
```    c  classes
    f  functions
    m  class members
    v  variables
    I  name referring a module defined in other file
    i  modules
    x  name referring a class/variable/function/module defined in other module
    z  function parameters [off]
    l  local variables [off]
```
Also the `*symbols-outline-ctags-output*` buffer has all the info, so the parsing works.

**Comment by liushihao456** [comment]
Try setting `symbols-outline-ignore-variable-symbols` to nil.

**Comment by artelse** [comment]
Than only constants and variables are shown and no functions. So it is either functions or variables and no functions defined in classes. For reference, here's the output of ctags of some test python file:
```
{"_type": "tag", "name": "test_variable", "line": 10, "kind": "variable"}
{"_type": "tag", "name": "test_func", "line": 13, "kind": "function", "signature": "(self)"}
{"_type": "tag", "name": "self", "line": 13, "kind": "parameter", "scope": "test_func", "scopeKind": "function"}
{"_type": "tag", "name": "AnotherWindow", "line": 17, "kind": "class"}
{"_type": "tag", "name": "__init__", "line": 23, "kind": "member", "signature": "(self)", "scope": "AnotherWindow", "scopeKind": "class"}
{"_type": "tag", "name": "self", "line": 23, "kind": "parameter", "scope": "AnotherWindow.__init__", "scopeKind": "member"}
{"_type": "tag", "name": "layout", "line": 25, "kind": "local", "scope": "AnotherWindow.__init__", "scopeKind": "member"}
{"_type": "tag", "name": "MainWindow", "line": 31, "kind": "class"}
{"_type": "tag", "name": "__init__", "line": 32, "kind": "member", "signature": "(self)", "scope": "MainWindow", "scopeKind": "class"}
{"_type": "tag", "name": "self", "line": 32, "kind": "parameter", "scope": "MainWindow.__init__", "scopeKind": "member"}
{"_type": "tag", "name": "show_new_window", "line": 40, "kind": "member", "signature": "(self, checked)", "scope": "MainWindow", "scopeKind": "class"}
{"_type": "tag", "name": "self", "line": 40, "kind": "parameter", "scope": "MainWindow.show_new_window", "scopeKind": "member"}
{"_type": "tag", "name": "checked", "line": 40, "kind": "parameter", "scope": "MainWindow.show_new_window", "scopeKind": "member"}
{"_type": "tag", "name": "app", "line": 45, "kind": "variable"}
{"_type": "tag", "name": "w", "line": 46, "kind": "variable"}
```

**Comment by artelse** [comment]
Catched the problem, tested `(image-type-available-p 'svg)` and showed my emacs wasn't compiled with SVG support and this broke the display.  Recompiled `--with-rsvg` and the `librsvg2-dev` lib installed.
Thanks for the help and the package!

**Comment by liushihao456** [comment]
Glad it works now. Thanks.
