### ISSUE TITLE
New feature request - keep enum and struct etc folded in c++ at start for vertical space saving

### ISSUE THREAD

**Issue by zijianyue** [liushihao456/symbols-outline.el#8]
<img width="319" alt="image" src="https://github.com/liushihao456/symbols-outline.el/assets/6119928/53aa688d-9f07-414f-a5e3-63bda487664b">

**Comment by liushihao456** [comment]
Added the customization variable `symbols-outline-initial-folded-node-kinds`. Please check out the latest update.

To achieve your purpose, you can set the variable like below:

```
(with-eval-after-load 'symbols-outline
  (setq symbols-outline-initial-folded-node-kinds '("enum" "struct")))
```

**Comment by zijianyue** [comment]
OK，it works well.
